### ISSUE TITLE
I have the terraria 1.4.4.0 source

### ISSUE THREAD

**Issue by BushTrain460615** [MemeHoovy/Terraria-1.4.3.6#1]
<img width="141" alt="Screenshot 2022-09-28 at 10 24 32 AM" src="https://user-images.githubusercontent.com/72326501/192820024-221a6705-8f8c-4c7f-a651-c10f4d22c20c.png">

**Comment by MemeHoovy** [comment]
> <img alt="Screenshot 2022-09-28 at 10 24 32 AM" width="141" src="https://user-images.githubusercontent.com/72326501/192820024-221a6705-8f8c-4c7f-a651-c10f4d22c20c.png">

wtf? how did you get that?

**Comment by BushTrain460615** [comment]
I updated terraria

**Comment by BushTrain460615** [comment]
<img width="1000" alt="Screenshot 2022-09-28 at 10 33 54 AM" src="https://user-images.githubusercontent.com/72326501/192822293-56ba8f5d-7aea-42ca-9079-0d74ba524c26.png">

**Comment by MemeHoovy** [comment]
> <img alt="Screenshot 2022-09-28 at 10 33 54 AM" width="1000" src="https://user-images.githubusercontent.com/72326501/192822293-56ba8f5d-7aea-42ca-9079-0d74ba524c26.png">

oh

**Comment by BushTrain460615** [comment]
<img width="400" alt="Screenshot 2022-09-28 at 10 35 11 AM" src="https://user-images.githubusercontent.com/72326501/192822573-5a6d4da8-8686-41ac-96c0-d3ad3ac706fc.png">

**Comment by MemeHoovy** [comment]
> <img alt="Screenshot 2022-09-28 at 10 35 11 AM" width="400" src="https://user-images.githubusercontent.com/72326501/192822573-5a6d4da8-8686-41ac-96c0-d3ad3ac706fc.png">

that's cool, I use ILSpy btw to decompile terraria
